// Generates the git-tag -> release-date map consumed by the `/changelog` render
// path (app/lib/changelog-dates.ts). The pure core (parseTagDates) is unit-tested
// offline with fixture git output; resolveTagDates reads every `v*` tag's date in
// one `for-each-ref` call behind an injectable RunGit seam and fails loud — a
// non-zero git exit or an empty tag set throws rather than writing a silent empty
// map that would render every released version as "Unreleased" (the shallow-clone
// deploy build is exactly that failure mode). A thin spawnSync CLI wraps it.
//
// Regenerate: bun run build-indexes (chained) or `bun scripts/build-changelog-dates.ts`.

import { spawnSync } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";

export type RunGit = (args: string[]) => {
  status: number | null;
  stdout: string;
  error?: Error | undefined;
};

export function parseTagDates(raw: string): Record<string, string> {
  const dates: Record<string, string> = {};
  for (const line of raw.split("\n")) {
    if (line.trim() === "") {
      continue;
    }
    const space = line.indexOf(" ");
    if (space === -1) {
      continue;
    }
    const version = line.slice(0, space);
    const date = line.slice(space + 1).trim();
    dates[version] = date;
  }
  return dates;
}

export function resolveTagDates(run: RunGit): Record<string, string> {
  // creatordate = tagger date for an annotated tag, commit date for a lightweight
  // tag; %(refname:short) yields the tag name (e.g. v0.20.4).
  const result = run([
    "for-each-ref",
    "--format=%(refname:short) %(creatordate:short)",
    "refs/tags/v*",
  ]);
  if (result.error || result.status !== 0) {
    const detail = result.error ? `: ${result.error.message}` : ` (exit ${result.status})`;
    throw new Error(`git for-each-ref refs/tags/v* failed${detail}`);
  }
  const dates = parseTagDates(result.stdout ?? "");
  if (Object.keys(dates).length === 0) {
    // empty-set-guard: a shallow deploy clone with no tags must fail loud, not
    // render every released version as "Unreleased".
    throw new Error(
      "no v* tags found — fetch tags before building (deploy-docs.yml needs fetch-tags/fetch-depth: 0)",
    );
  }
  return dates;
}

if (import.meta.main) {
  const run: RunGit = (args) => {
    const p = spawnSync("git", args, { encoding: "utf8" });
    return { status: p.status, stdout: p.stdout ?? "", error: p.error };
  };
  try {
    const dates = resolveTagDates(run);
    const outDir = join(import.meta.dir, "..", "app", "generated");
    mkdirSync(outDir, { recursive: true });
    const banner = "// Generated by build-changelog-dates.ts — do not edit.";
    const body = `${banner}\n\nexport const CHANGELOG_TAG_DATES: Record<string, string> = ${JSON.stringify(dates, null, 2)} as const;\n`;
    writeFileSync(join(outDir, "changelog-dates.ts"), body);
    console.log(`changelog-dates.ts: ${Object.keys(dates).length} tag dates`);
  } catch (err) {
    process.stderr.write(`${err instanceof Error ? err.message : String(err)}\n`);
    process.exit(1);
  }
}
