import { existsSync, readFileSync, writeFileSync } from "node:fs";
import * as path from "node:path";

export const AGENTS_BLOCK_START = "<!-- defold-typescript:agents:start -->";
export const AGENTS_BLOCK_END = "<!-- defold-typescript:agents:end -->";

export interface RunInitAgentsOptions {
  readonly cwd: string;
  // Re-sync an already-present contract file. Defaults to true so the standalone
  // `init-agents` verb always refreshes; the `init` scaffold passes its own
  // `--force` so a plain re-init leaves an existing contract untouched.
  readonly force?: boolean;
}

export interface RunInitAgentsResult {
  readonly written: string[];
}

// Versionless and path-stable on purpose: every pointer resolves under
// `node_modules/@defold-typescript/`, which the install command swaps under the
// same paths, so re-runs stay byte-identical and nothing drifts. Never embed a
// version number or an absolute host path here.
export function renderAgentsBlock(): string {
  return [
    "<!-- Auto-generated by defold-typescript — edits between the markers are overwritten on the next `init-agents` run. Put your own notes outside the markers. -->",
    "This project uses defold-typescript: author game logic in TypeScript and the",
    "toolchain transpiles it to Lua for Defold.",
    "",
    "Docs (refreshed on every install):",
    "- node_modules/@defold-typescript/docs/llms.txt — the map; start here.",
    "- node_modules/@defold-typescript/docs/llms-full.txt — full corpus; grep it, never read it whole.",
    "- node_modules/@defold-typescript/docs/guide/<page>.md — individual guide pages.",
    "- Authoritative typed API: @defold-typescript/types/generated/*.d.ts, plus",
    "  @defold-typescript/types/src/core-types.ts and src/engine-globals.d.ts.",
    "- Engine and Lua manuals (index; fetch the specific page you need): https://defold.com/llms.txt",
    "If those paths are absent, run the project's install command first.",
    "",
    "Hard rules:",
    "- Never hand-edit or commit `build/`; the transpiler generates it.",
    "- Never hand-edit or commit `.defold-types/`; the resolver generates it.",
    "- One `defineScript`/`defineGuiScript`/`defineRenderScript` factory per file; a script",
    "  file compiles to `.ts.script` / `.ts.gui_script` / `.ts.render_script`.",
    "- Files with no `define*` export are plain modules for shared functions and game state;",
    "  they compile to `.lua`, which is expected and encouraged.",
    "- Do not call the generic form `defineScript<T>(...)` / `defineGuiScript<T>(...)`; the factory",
    "  goes undetected and the file silently compiles to a `.lua` module instead of a script —",
    "  annotate `init(): T` instead.",
  ].join("\n");
}

export function renderClaudeBlock(): string {
  return "@AGENTS.md";
}

function wrap(body: string): string {
  return `${AGENTS_BLOCK_START}\n${body}\n${AGENTS_BLOCK_END}`;
}

// Replace the inclusive between-markers span when both markers are present;
// otherwise append the freshly-wrapped block after exactly one blank line,
// leaving every other byte of `existing` untouched.
function patchManagedBlock(existing: string, body: string): string {
  const wrapped = wrap(body);
  const startIdx = existing.indexOf(AGENTS_BLOCK_START);
  const endIdx = existing.indexOf(AGENTS_BLOCK_END);
  if (startIdx !== -1 && endIdx > startIdx) {
    const after = endIdx + AGENTS_BLOCK_END.length;
    return existing.slice(0, startIdx) + wrapped + existing.slice(after);
  }
  if (existing.trim() === "") {
    return `${wrapped}\n`;
  }
  return `${existing.replace(/\n+$/, "")}\n\n${wrapped}\n`;
}

export function runInitAgents(opts: RunInitAgentsOptions): RunInitAgentsResult {
  const { cwd, force = true } = opts;
  const written: string[] = [];

  const agentsPath = path.join(cwd, "AGENTS.md");
  if (!existsSync(agentsPath)) {
    writeFileSync(agentsPath, patchManagedBlock("", renderAgentsBlock()));
    written.push("AGENTS.md");
  } else if (force) {
    const agentsExisting = readFileSync(agentsPath, "utf8");
    writeFileSync(agentsPath, patchManagedBlock(agentsExisting, renderAgentsBlock()));
    written.push("AGENTS.md");
  }

  const claudePath = path.join(cwd, "CLAUDE.md");
  if (!existsSync(claudePath)) {
    writeFileSync(claudePath, `${renderClaudeBlock()}\n`);
    written.push("CLAUDE.md");
  } else if (force) {
    const claudeExisting = readFileSync(claudePath, "utf8");
    if (claudeExisting.trim() !== renderClaudeBlock()) {
      writeFileSync(claudePath, patchManagedBlock(claudeExisting, renderClaudeBlock()));
      written.push("CLAUDE.md");
    }
  }

  return { written };
}
