import { existsSync, mkdirSync, readFileSync, rmSync, writeFileSync } from "node:fs";
import * as path from "node:path";
import { DEFAULT_INCLUDE } from "@defold-typescript/transpiler";
import { resolveBootPathScripts } from "./boot-path";
import {
  type BuildConfig,
  computeOutputRel,
  detectSourceOutputKind,
  isFileIncluded,
  readBuildConfig,
} from "./build-output";
import { DEBUG_LAUNCHER_REL } from "./debug-launcher";
import { normalizeScannedPath, scanFilesSync } from "./scan";
import { isSkipped } from "./script-kind";
import {
  VSCODE_EXTENSIONS_REL,
  VSCODE_LAUNCH_REL,
  writeDebugRecommendation,
  writeVscodeDebugLauncher,
  writeVscodeLaunch,
} from "./vscode-debug-scaffold";

// Our pinned release URL, mirrored from `packages/docs/guide/debugging.md`. The
// `lldebugger-url` leak guard forbids the upstream ts-defold URL, so this must
// stay equal to the guide's snapshot URL.
export const LLDEBUGGER_URL =
  "https://github.com/defold-typescript/toolchain/releases/download/lldebugger-v1/lldebugger.zip";

// The prior step shipped a single skip-marker block with the `declare module`
// inline. That form fails `tsc` under `moduleResolution: Bundler` (Bug 08), so
// the declaration moved to an ambient `.d.ts`. The marker is kept only as the
// legacy-detection needle for the upgrade path below.
export const LEGACY_BOOTSTRAP_MARKER =
  "// lldebugger-bootstrap: debug entry, inert in release builds";

// Where earlier releases always wrote the ambient `.d.ts`. The live declaration
// now lands beside the chosen entry script (`ambientDtsRel`), so this is kept
// only as the path whose tool-written leftover is cleaned up.
export const AMBIENT_DTS_REL = "src/lldebugger.debug.d.ts";

// The ambient declaration regenerated by `setup-debug`. `@noResolution` keeps
// TSTL from rewriting the literal module path so the emit stays
// `require("lldebugger.debug")`; in a `.d.ts` the declaration type-checks clean
// (the inline form in a `.ts` did not — Bug 08).
export const AMBIENT_DECLARATION = `/** @noResolution */
declare module "lldebugger.debug" {
  export function start(): void;
}
`;

// Managed-block sentinels. A re-run locates the single BEGIN…END pair and
// refreshes the enclosed text if it drifted, so wording changes self-heal.
// They are `//` line comments, stripped by TSTL, so they never reach the
// emitted `.ts.script`.
export const BLOCK_BEGIN = "// defold-typescript:setup-debug BEGIN — managed block, do not edit";
export const BLOCK_END = "// defold-typescript:setup-debug END";

// The canonical managed block: import + gated start, marker-free, no
// `declare module` (that lives in the ambient `.d.ts`). Mirrors the snippet in
// `packages/docs/guide/debugging.md` exactly; a guide-comparison test locks the two.
// The blank line before END keeps Biome's organizeImports assist from gluing
// the END comment onto a following import as its leading comment (which would
// then demand a blank line before the whole group). With blank lines on both
// sides of END, an import injected above the user's own imports stays clean.
const MANAGED_BLOCK = `${BLOCK_BEGIN}
import * as lldebugger from "lldebugger.debug";

if (sys.get_engine_info().is_debug) {
  lldebugger.start();
}

${BLOCK_END}`;

const FACTORY_NAMES = ["defineScript", "defineGuiScript", "defineRenderScript"] as const;

const MANUAL_STEPS: readonly string[] = [
  "Install the Local Lua Debugger extension (tomblind.local-lua-debugger-vscode) in VS Code.",
  "Run Project -> Fetch Libraries in the Defold editor to download the lldebugger module.",
];

function isProjectHeader(line: string): boolean {
  return line.trim() === "[project]";
}

function isSectionHeader(line: string): boolean {
  return /^\[.+\]\s*$/.test(line.trim());
}

// Line-aware INI edit: find the max `dependencies#N` under `[project]` and
// append `#(N+1)`; skip when the URL already appears. Deliberately no TOML/INI
// parser — `game.project` is a flat INI the engine writes itself.
export function addLldebuggerDependency(gameProjectText: string): string {
  const lines = gameProjectText.split("\n");
  if (!lines.some(isProjectHeader)) {
    throw new Error(
      "defold-typescript setup-debug: game.project has no [project] section; this is not a Defold project.",
    );
  }
  if (gameProjectText.includes(LLDEBUGGER_URL)) {
    return gameProjectText;
  }

  let inProject = false;
  let maxIndex = -1;
  let lastDepLine = -1;
  let lastProjectLine = -1;
  for (let i = 0; i < lines.length; i++) {
    const line = lines[i] ?? "";
    if (isSectionHeader(line)) {
      inProject = isProjectHeader(line);
      if (inProject) {
        lastProjectLine = i;
      }
      continue;
    }
    if (inProject && line.trim() !== "") {
      lastProjectLine = i;
      const dep = line.match(/^dependencies#(\d+)\s*=/);
      if (dep?.[1] !== undefined) {
        const n = Number(dep[1]);
        if (n > maxIndex) {
          maxIndex = n;
        }
        lastDepLine = i;
      }
    }
  }

  const newLine = `dependencies#${maxIndex + 1} = ${LLDEBUGGER_URL}`;
  const insertAt = (lastDepLine >= 0 ? lastDepLine : lastProjectLine) + 1;
  lines.splice(insertAt, 0, newLine);
  return lines.join("\n");
}

// The exact text the prior step prepended (snippet + its trailing newline);
// matched verbatim so a legacy block is upgraded in place rather than stacked.
const LEGACY_BLOCK = `${LEGACY_BOOTSTRAP_MARKER}
/** @noResolution */
declare module "lldebugger.debug" {
  export function start(): void;
}

import * as lldebugger from "lldebugger.debug";

if (sys.get_engine_info().is_debug) {
  lldebugger.start();
}
`;

export type FileAction = "injected" | "refreshed" | "unchanged" | "removed";

export interface UpsertResult {
  readonly text: string;
  readonly action: FileAction;
}

function occurrences(haystack: string, needle: string): number {
  return haystack.split(needle).length - 1;
}

// retired-orphan-audit: the injectDebugBootstrap wrapper was retired; this is
// the live entry point every caller and test now reaches.
// Locate the single managed BEGIN…END pair and act on its three states:
// absent (inject or legacy-upgrade), canonical (no-op), drifted (splice-
// replace). A malformed region (lone or duplicate / out-of-order sentinels)
// is refused so the tool never deletes user code by guessing the extent.
export function upsertManagedBlock(source: string): UpsertResult {
  const begins = occurrences(source, BLOCK_BEGIN);
  const ends = occurrences(source, BLOCK_END);

  if (begins !== ends || begins > 1) {
    throw new Error(
      "defold-typescript setup-debug: malformed managed block (mismatched, duplicate, or out-of-order sentinels); refusing to edit.",
    );
  }

  if (begins === 1) {
    const beginAt = source.indexOf(BLOCK_BEGIN);
    const endAt = source.indexOf(BLOCK_END);
    if (endAt < beginAt) {
      throw new Error(
        "defold-typescript setup-debug: malformed managed block (END before BEGIN); refusing to edit.",
      );
    }
    const regionEnd = endAt + BLOCK_END.length;
    const region = source.slice(beginAt, regionEnd);
    if (region === MANAGED_BLOCK) {
      return { text: source, action: "unchanged" };
    }
    const text = source.slice(0, beginAt) + MANAGED_BLOCK + source.slice(regionEnd);
    return { text, action: "refreshed" };
  }

  if (source.includes(LEGACY_BLOCK)) {
    return { text: source.replace(LEGACY_BLOCK, `${MANAGED_BLOCK}\n`), action: "refreshed" };
  }

  return { text: `${MANAGED_BLOCK}\n\n${source}`, action: "injected" };
}

export interface StripResult {
  readonly text: string;
  readonly removed: boolean;
}

// Remove the single managed BEGIN…END pair (and the blank lines the inject
// prepended) so the block survives in exactly the chosen entry script. A file
// with no block is left untouched; a malformed region is refused, mirroring
// `upsertManagedBlock`, so the tool never guesses the extent and deletes code.
export function stripManagedBlock(source: string): StripResult {
  const begins = occurrences(source, BLOCK_BEGIN);
  const ends = occurrences(source, BLOCK_END);

  if (begins === 0 && ends === 0) {
    return { text: source, removed: false };
  }
  if (begins !== ends || begins > 1) {
    throw new Error(
      "defold-typescript setup-debug: malformed managed block (mismatched, duplicate, or out-of-order sentinels); refusing to edit.",
    );
  }

  const beginAt = source.indexOf(BLOCK_BEGIN);
  const endAt = source.indexOf(BLOCK_END);
  if (endAt < beginAt) {
    throw new Error(
      "defold-typescript setup-debug: malformed managed block (END before BEGIN); refusing to edit.",
    );
  }
  const regionEnd = endAt + BLOCK_END.length;
  const after = source.slice(regionEnd).replace(/^\n{1,2}/, "");
  return { text: source.slice(0, beginAt) + after, removed: true };
}

function hasFactoryCall(text: string): boolean {
  return FACTORY_NAMES.some((name) => text.includes(`${name}(`));
}

type ProjectScanner = (cwd: string, pattern: string) => string[];

// `setup-debug`'s only hard precondition is `game.project`, and most projects it
// wires have never run `init`, so a missing or unparseable `tsconfig.json` is
// the `src/`-rooted default rather than the hard failure `readBuildConfig`
// raises for the build.
export function resolveSetupDebugConfig(cwd: string): BuildConfig {
  try {
    return readBuildConfig(cwd);
  } catch {
    return { outDir: undefined, include: DEFAULT_INCLUDE };
  }
}

interface IncludedSource {
  readonly rel: string;
  readonly text: string;
}

// The one source set the command works from: every configured `include` pattern
// unioned the way the build assembles its own program, minus the declarations
// and generated trees that are never an entry script. Each file is read once so
// the factory-call filter, the output map and the stale-block walk share it.
export function includedProductionSources(
  cwd: string,
  config: BuildConfig,
  scanner: ProjectScanner = scanFilesSync,
): IncludedSource[] {
  const rels = new Set<string>();
  for (const pattern of config.include) {
    for (const match of scanner(cwd, pattern)) {
      const rel = normalizeScannedPath(match);
      if (isSkipped(rel) || rel.endsWith(".d.ts")) {
        continue;
      }
      rels.add(rel);
    }
  }
  return [...rels].sort().map((rel) => ({ rel, text: readFileSync(path.join(cwd, rel), "utf8") }));
}

export function findEntryScriptCandidates(
  cwd: string,
  config: BuildConfig = resolveSetupDebugConfig(cwd),
  scanner: ProjectScanner = scanFilesSync,
): string[] {
  return includedProductionSources(cwd, config, scanner)
    .filter((source) => hasFactoryCall(source.text))
    .map((source) => source.rel);
}

// The declaration has to reach the program the build assembles from `include`,
// and the target's own directory is the one place a pattern that matched the
// target also matches a `*.ts` sibling.
export function ambientDtsRel(target: string): string {
  const dir = path.posix.dirname(target);
  return dir === "." ? "lldebugger.debug.d.ts" : path.posix.join(dir, "lldebugger.debug.d.ts");
}

function notConfiguredInput(rel: string, config: BuildConfig): string {
  return `defold-typescript setup-debug: ${rel} is not covered by the tsconfig.json "include" patterns (${config.include.join(", ")}); add a pattern that matches it, or choose a script that is already a configured input.`;
}

// An `include` pattern can match a path the build never compiles as an input.
// The refusal names the cause, because "not a production source" is opaque next
// to a file the user can see their own glob matching. Both target routes reach
// this through `rejectedTargetReason`.
function notProductionSource(rel: string, config: BuildConfig): string {
  const patterns = config.include.join(", ");
  if (rel.endsWith(".d.ts")) {
    return `defold-typescript setup-debug: ${rel} is a declaration file, and the debugger bootstrap has to live in the .ts entry script the build compiles (configured "include": ${patterns}); pass that script with --script instead.`;
  }
  const segment = rel.split("/").find((part) => isSkipped(part)) ?? rel;
  return `defold-typescript setup-debug: ${rel} sits under a generated or dependency tree ("${segment}"), so it is not one of the compiled inputs even though an "include" pattern matches it (${patterns}); choose an entry script from your own sources.`;
}

// The single place either target route decides why a path that exists is still
// not an admissible target, so the boot branch and `--script` cannot drift into
// describing the same file two different ways.
function rejectedTargetReason(rel: string, config: BuildConfig): string {
  return isFileIncluded(rel, config.include)
    ? notProductionSource(rel, config)
    : notConfiguredInput(rel, config);
}

// A collection naming a `.ts.script` component claims the build writes it from a
// TypeScript source. When nothing configured does, guessing a different script is
// what edits the wrong file, so the claim fails loudly instead.
function unresolvedBootTarget(
  entry: { readonly candidate: string; readonly trace: readonly string[] },
  cwd: string,
  config: BuildConfig,
): string {
  if (existsSync(path.join(cwd, entry.candidate))) {
    return rejectedTargetReason(entry.candidate, config);
  }
  const component = entry.trace[entry.trace.length - 1] ?? entry.candidate;
  return `defold-typescript setup-debug: the collection names the component ${component}, but no source the tsconfig.json "include" patterns cover (${config.include.join(", ")}) builds to it; add a pattern that matches its source, or drop the component from the collection.`;
}

function declarationNotIncluded(target: string, dtsRel: string, config: BuildConfig): string {
  return `defold-typescript setup-debug: the debugger declaration for ${target} belongs at ${dtsRel}, which no tsconfig.json "include" pattern covers (${config.include.join(", ")}); add "${dtsRel}" to "include" so the compiler picks it up.`;
}

export interface SetupDebugOptions {
  readonly cwd: string;
  readonly script?: string;
  readonly json?: boolean;
  readonly chooseScript?: (candidates: string[]) => Promise<string>;
  readonly scanFiles?: ProjectScanner;
  readonly config?: BuildConfig;
}

export interface SetupDebugResult {
  readonly ok: boolean;
  readonly written: string[];
  readonly actions: Record<string, FileAction>;
  readonly manualSteps: readonly string[];
  readonly error?: string;
  readonly addedTo?: string;
  readonly removedFrom?: string[];
  readonly bootPath?: string[];
}

interface ResolvedTarget {
  readonly target: string;
  readonly bootPath: string[];
}

function failure(error: string): SetupDebugResult {
  return { ok: false, written: [], actions: {}, manualSteps: MANUAL_STEPS, error };
}

async function defaultChooseScript(candidates: string[]): Promise<string> {
  const { select } = await import("@inquirer/prompts");
  return select({
    message: "Select the entry script to receive the debugger bootstrap:",
    choices: candidates.map((candidate) => ({ name: candidate, value: candidate })),
  });
}

async function pickCandidate(
  candidates: string[],
  opts: SetupDebugOptions,
): Promise<string | SetupDebugResult> {
  if (candidates.length === 1) {
    return candidates[0] as string;
  }
  const chooser = opts.chooseScript ?? (opts.json ? undefined : defaultChooseScript);
  if (chooser === undefined) {
    return failure(
      `defold-typescript setup-debug: multiple entry scripts found (${candidates.join(", ")}); pass --script to choose one.`,
    );
  }
  return chooser(candidates);
}

// Prefer a script on the Defold boot path (game.project -> collections ->
// `.ts.script`); fall back to the configured-input factory-call scan only when
// the boot path reaches no script. `--script` always wins, carrying the
// boot-path trace for the report when the named file is itself on the path.
// Every target is a member of `includedProductionSources`, not merely a path
// some `include` glob matches, so the command never edits a file the build does
// not compile; and a `.ts.script` component the boot path reaches that no
// configured source builds fails rather than falling through to the scan.
async function resolveTargetScript(
  opts: SetupDebugOptions,
  config: BuildConfig,
  sources: readonly IncludedSource[],
): Promise<ResolvedTarget | SetupDebugResult> {
  const { cwd } = opts;
  const script = opts.script === undefined ? undefined : normalizeScannedPath(opts.script);

  // A collection names a component by the path the build *writes*, which under
  // an `outDir` is nowhere near its source. Mapping each configured source
  // forward through the build's own output math and reversing that map keeps
  // the two spellings in agreement; stripping `.script` off the resource path
  // only ever held for an alongside build.
  const sourceByOutput = new Map<string, string>();
  for (const { rel, text } of sources) {
    sourceByOutput.set(computeOutputRel(rel, config, detectSourceOutputKind(text)), rel);
  }
  // Two ordered resolution steps, never a filter: the forward output map covers
  // the `outDir` case, and identity against the production set covers a
  // component whose source emits as a plain module, whose forward output is a
  // `.lua` the collection never names. Only after both miss is the entry
  // unresolved, and a resolved source is a member of `sources` by construction.
  const productionRels = new Set(sources.map((source) => source.rel));
  const bootEntries = resolveBootPathScripts(cwd).map((entry) => ({
    ...entry,
    source:
      sourceByOutput.get(`${entry.candidate}.script`) ??
      (productionRels.has(entry.candidate) ? entry.candidate : undefined),
  }));

  if (script !== undefined) {
    if (!existsSync(path.join(cwd, script))) {
      return failure(`defold-typescript setup-debug: script not found: ${script}`);
    }
    if (!productionRels.has(script)) {
      return failure(rejectedTargetReason(script, config));
    }
    const onPath = bootEntries.find((entry) => entry.source === script);
    return { target: script, bootPath: onPath?.trace ?? [] };
  }

  if (bootEntries.length > 0) {
    const unresolved = bootEntries.find((entry) => entry.source === undefined);
    if (unresolved !== undefined) {
      return failure(unresolvedBootTarget(unresolved, cwd, config));
    }
    const picked = await pickCandidate(
      bootEntries.map((entry) => entry.source as string),
      opts,
    );
    if (typeof picked !== "string") {
      return picked;
    }
    const onPath = bootEntries.find((entry) => entry.source === picked);
    return { target: picked, bootPath: onPath?.trace ?? [] };
  }

  const scanned = sources
    .filter((source) => hasFactoryCall(source.text))
    .map((source) => source.rel);
  if (scanned.length === 0) {
    return failure(
      `defold-typescript setup-debug: no entry script with a lifecycle factory call found in the configured inputs (${config.include.join(", ")}).`,
    );
  }
  const picked = await pickCandidate(scanned, opts);
  if (typeof picked !== "string") {
    return picked;
  }
  return { target: picked, bootPath: [] };
}

export async function runSetupDebug(opts: SetupDebugOptions): Promise<SetupDebugResult> {
  const { cwd } = opts;
  const gameProjectPath = path.join(cwd, "game.project");
  if (!existsSync(gameProjectPath)) {
    return failure(
      "defold-typescript setup-debug: no game.project here; this is not a Defold project.",
    );
  }

  const config = opts.config ?? resolveSetupDebugConfig(cwd);
  const sources = includedProductionSources(cwd, config, opts.scanFiles);

  const resolved = await resolveTargetScript(opts, config, sources);
  if (!("target" in resolved)) {
    return resolved;
  }
  const { target, bootPath } = resolved;

  // Both destinations are settled before the first write, so a project the
  // command cannot wire is left byte-identical rather than half-edited.
  const dtsRel = ambientDtsRel(target);
  if (!isFileIncluded(dtsRel, config.include)) {
    return failure(declarationNotIncluded(target, dtsRel, config));
  }

  const written: string[] = [];
  const actions: Record<string, FileAction> = {};

  const dtsPath = path.join(cwd, dtsRel);
  mkdirSync(path.dirname(dtsPath), { recursive: true });
  const existingDts = existsSync(dtsPath) ? readFileSync(dtsPath, "utf8") : null;
  if (existingDts === null) {
    writeFileSync(dtsPath, AMBIENT_DECLARATION);
    actions[dtsRel] = "injected";
  } else if (existingDts !== AMBIENT_DECLARATION) {
    writeFileSync(dtsPath, AMBIENT_DECLARATION);
    actions[dtsRel] = "refreshed";
  } else {
    actions[dtsRel] = "unchanged";
  }
  written.push(dtsRel);

  // A declaration an earlier run left at the legacy path would reach the same
  // program as a second `declare module`, so a tool-written one is removed once
  // the live declaration lives elsewhere. A file whose content has drifted is
  // the user's, and is left alone.
  if (dtsRel !== AMBIENT_DTS_REL) {
    const legacyPath = path.join(cwd, AMBIENT_DTS_REL);
    if (existsSync(legacyPath) && readFileSync(legacyPath, "utf8") === AMBIENT_DECLARATION) {
      rmSync(legacyPath);
      actions[AMBIENT_DTS_REL] = "removed";
    }
  }

  const scriptPath = path.join(cwd, target);
  const source = readFileSync(scriptPath, "utf8");
  const { text: injected, action: scriptAction } = upsertManagedBlock(source);
  if (injected !== source) {
    writeFileSync(scriptPath, injected);
  }
  actions[target] = scriptAction;
  written.push(target);

  const gameProjectText = readFileSync(gameProjectPath, "utf8");
  const updated = addLldebuggerDependency(gameProjectText);
  if (updated !== gameProjectText) {
    writeFileSync(gameProjectPath, updated);
    actions["game.project"] = "injected";
  } else {
    actions["game.project"] = "unchanged";
  }
  written.push("game.project");

  // Keep the bootstrap in exactly one script: strip a stale managed block from
  // every other configured source. A malformed block elsewhere is left alone
  // (the strip refuses it) rather than aborting the wiring of the chosen target.
  const removedFrom: string[] = [];
  for (const { rel, text: otherSource } of sources) {
    if (rel === target) {
      continue;
    }
    const otherPath = path.join(cwd, rel);
    let stripped: StripResult;
    try {
      stripped = stripManagedBlock(otherSource);
    } catch {
      continue;
    }
    if (stripped.removed) {
      writeFileSync(otherPath, stripped.text);
      actions[rel] = "removed";
      removedFrom.push(rel);
    }
  }
  removedFrom.sort();

  // The editor half of the debug path: the launch configuration derived from
  // this project's own inputs, the Bun launcher it runs, and the extension that
  // provides the `lua-local` adapter.
  const launchAction = writeVscodeLaunch(cwd, config, "create");
  if (launchAction !== null) {
    actions[VSCODE_LAUNCH_REL] = launchAction;
    written.push(VSCODE_LAUNCH_REL);
  }
  actions[DEBUG_LAUNCHER_REL] = writeVscodeDebugLauncher(cwd);
  written.push(DEBUG_LAUNCHER_REL);
  actions[VSCODE_EXTENSIONS_REL] = writeDebugRecommendation(cwd);
  written.push(VSCODE_EXTENSIONS_REL);

  return {
    ok: true,
    written,
    actions,
    manualSteps: MANUAL_STEPS,
    addedTo: target,
    removedFrom,
    bootPath,
  };
}
