/**
 * Which shipping declaration surface carries which hand-authored `@example`
 * translation.
 *
 * The store is not single-surface: an FQN maps to one translation per distinct
 * example body (`example-store.ts`), and sibling entries serve *different*
 * targets, because an older target keeps shipping the body a re-pin replaced.
 * Judging every translation against the default entrypoint is therefore the
 * wrong comparison — it reports the editor examples as unresolved names and
 * measures bodies against signatures from a target that never shipped them.
 *
 * Membership is read from each target's own manifest documents and never
 * inferred from hash recency, because the same body legitimately ships in a
 * current target and a versioned one at the same time.
 */
import { basename, dirname, resolve } from "node:path";
import { parseDefoldApiDoc } from "../src/api-doc";
import { htmlToCodeText } from "../src/doc-comment";
import { hashExampleSource, type TranslationStore } from "../src/example-store";
import { buildVersionedSurfaceFiles, renderMaterializedKindIndex } from "./materialize-version";
import {
  type ApiTarget,
  type KindManifestEntry,
  loadApiTargets,
  loadTargetEditorModules,
  loadTargetModules,
  type ModuleManifestEntry,
  RESTRICTED_NAMESPACES,
  RESTRICTED_SRC_AUGMENTATIONS,
  targetKindManifest,
} from "./regen";

const PACKAGE_ROOT = resolve(import.meta.dir, "..");

// A materialized surface exists only as bytes, but its module specifiers still
// resolve like a real one: `@defold-typescript/types/lifecycle` is found by
// walking up to the package's own `node_modules`. Rooting the virtual tree
// inside the package is what makes that walk reach the same place the CLI's
// on-disk `.defold-types/<id>/` does.
const VIRTUAL_ROOT = resolve(PACKAGE_ROOT, ".example-gate");

export interface SurfaceFile {
  /** Absolute path. Real for a committed surface, virtual for a materialized one. */
  readonly path: string;
  readonly contents: string;
}

export interface ExampleSurface {
  /** `<target>` for a root entrypoint, `<target>/kinds/<kind>` for a kind. */
  readonly id: string;
  readonly targetId: string;
  /** `null` for the aggregate root entrypoint. */
  readonly kind: string | null;
  readonly origin: "committed" | "materialized";
  readonly entry: string;
  /** Empty for a committed surface; the whole in-memory tree for a materialized one. */
  readonly virtualFiles: readonly SurfaceFile[];
  /** The manifest modules this entrypoint reaches, as `moduleKey` values. */
  readonly modules: ReadonlySet<string>;
  /**
   * The names this entrypoint *exports*, as opposed to the ambient declarations
   * it pulls in. A kind subpath re-exports its factory (`defineScript` and
   * friends); a user writing a script imports them, so an example fragment
   * compiled without them is judged against a surface nobody consumes.
   */
  readonly exports: SurfaceExports;
}

export interface SurfaceExports {
  readonly values: readonly string[];
  readonly types: readonly string[];
}

const NO_EXPORTS: SurfaceExports = { values: [], types: [] };

/**
 * The package root's export set. `index.d.ts` ends in `export * from
 * "./src/index"`, which re-exports every kind factory and the script-property
 * types — but not a kind's `extraExports`, which stay on the editor subpath. A
 * versioned root is generated by `generateVersionIndex` and ends in a bare
 * `export {}`, so it exports nothing and takes `NO_EXPORTS` instead.
 *
 * Nothing here is taken on trust: the gate imports these names, so a root that
 * stopped exporting one fails every unit on that surface with TS2305 rather than
 * quietly widening what counts as fragment context.
 */
function defaultRootExports(manifest: readonly KindManifestEntry[]): SurfaceExports {
  return {
    values: manifest.map((entry) => entry.factory),
    types: ["ScriptProperties", "ScriptProperty"],
  };
}

/**
 * The kind subpath's export set, read from the same manifest entry
 * `generateKindIndex` and `renderMaterializedKindIndex` render their export
 * clause from, so a kind that gains an export reaches the gate with no second
 * edit.
 */
function kindExports(entry: KindManifestEntry): SurfaceExports {
  return {
    values: [entry.factory, ...(entry.extraExports ?? [])],
    types: [
      ...(entry.extraTypeExports ?? []),
      ...(entry.propertyTypes === false ? [] : ["ScriptProperties", "ScriptProperty"]),
    ],
  };
}

/**
 * A manifest module's identity within a target. The lane has to be part of it:
 * `http`, `image`, `json` and `zlib` name *both* a runtime namespace and an
 * editor-VM one, so a bare namespace would put the runtime `zlib.inflate` on the
 * editor kind (which does not carry it) and vice versa.
 */
export function moduleKey(namespace: string, lane: "runtime" | "editor"): string {
  return `${lane}:${namespace}`;
}

export interface SkippedTarget {
  readonly id: string;
  readonly reason: string;
}

/** `<fqn>:<sourceHash>` — one authored translation, independent of surface. */
export function exampleIdentity(fqn: string, sourceHash: string): string {
  return `${fqn}:${sourceHash}`;
}

/**
 * Targets an offline gate cannot honestly cover. A `ref-doc` target resolves its
 * documents from a zip downloaded on demand, so nothing is vendored to compile
 * against. The exclusion is returned rather than left to a missing directory, so
 * vendoring such a target later is a visible change instead of a silent one.
 */
export function refDocSkippedTargets(
  targets: readonly ApiTarget[] = loadApiTargets(),
): SkippedTarget[] {
  return targets
    .filter((target) => (target.source ?? null) !== null)
    .map((target) => ({
      id: target.id,
      reason: `documents are not vendored (source kind "${target.source?.kind}")`,
    }));
}

function committedTargets(targets: readonly ApiTarget[] = loadApiTargets()): ApiTarget[] {
  return targets.filter((target) => (target.source ?? null) === null);
}

/**
 * The namespaces one kind entrypoint reaches, derived from the same manifests
 * `generateKindIndex` renders from. An `only` kind is built from its target's
 * editor documents and is disjoint from the runtime surface; every other kind
 * takes the universal set plus, for a restricted kind, its own namespace.
 */
function kindModules(
  entry: KindManifestEntry,
  runtime: readonly ModuleManifestEntry[],
  editor: readonly ModuleManifestEntry[],
): Set<string> {
  if (entry.only !== undefined) {
    return new Set(editor.map((module) => moduleKey(module.namespace, "editor")));
  }
  return new Set(
    runtime
      .map((module) => module.namespace)
      .filter(
        (namespace) =>
          !Object.hasOwn(RESTRICTED_NAMESPACES, namespace) || entry.restricted === namespace,
      )
      .map((namespace) => moduleKey(namespace, "runtime")),
  );
}

/**
 * Reproduce the CLI's materialized surface as an in-memory file map. Mirrors
 * `materializeRefDocSurface`: the generator builds the self-contained surface,
 * and this adds the per-kind subpaths through the production renderer. Only the
 * runtime kinds are rendered here — a target's editor kind is committed under
 * `generated/versions/<id>/kinds/`, so it is read from disk instead.
 */
async function materializedRuntimeKindFiles(
  target: ApiTarget,
  virtualRoot: string,
): Promise<{ files: SurfaceFile[]; kinds: { entry: KindManifestEntry; path: string }[] }> {
  const built = await buildVersionedSurfaceFiles(target);
  const files: SurfaceFile[] = built.map((file) => ({
    path: resolve(virtualRoot, file.path),
    contents: file.contents,
  }));

  const editorOwned = new Set(
    (target.editorModules ?? []).map((module) => module.outFile.replace(/\.d\.ts$/, "")),
  );
  const surfaceModules = files
    .filter((file) => dirname(file.path) === virtualRoot && file.path.endsWith(".d.ts"))
    .map((file) => basename(file.path).replace(/\.d\.ts$/, ""))
    .filter(
      (base) =>
        base !== "index" &&
        base !== "core-types" &&
        base !== "engine-globals" &&
        !editorOwned.has(base),
    )
    .sort();
  const universalModules = surfaceModules.filter(
    (base) =>
      !Object.hasOwn(RESTRICTED_NAMESPACES, base) &&
      !Object.hasOwn(RESTRICTED_SRC_AUGMENTATIONS, base),
  );

  const kinds: { entry: KindManifestEntry; path: string }[] = [];
  for (const entry of targetKindManifest(target)) {
    if (entry.only !== undefined) continue;
    const path = resolve(virtualRoot, "kinds", `${entry.kind}.d.ts`);
    files.push({
      path,
      contents: renderMaterializedKindIndex({
        kind: entry.kind,
        universalModules,
        restrictedModule:
          entry.restricted && surfaceModules.includes(entry.restricted) ? entry.restricted : null,
        restrictedAugmentations: surfaceModules.filter(
          (base) =>
            Object.hasOwn(RESTRICTED_SRC_AUGMENTATIONS, base) &&
            entry.restricted !== undefined &&
            RESTRICTED_SRC_AUGMENTATIONS[base] === entry.restricted,
        ),
      }),
    });
    kinds.push({ entry, path });
  }
  return { files, kinds };
}

/**
 * Every surface this gate can reach offline. Not the same as every surface a
 * user can install: the four families differ in how they exist, and conflating
 * them produces path claims that are simply false.
 *
 * 1. the default target's root and all four committed kind entrypoints;
 * 2. each versioned target's committed root, and its committed editor kinds —
 *    `regen.ts` filters the kind manifest to `entry.only !== undefined` before
 *    writing `versions/<id>/kinds/`, so that directory is never the runtime trio;
 * 3. versioned runtime kinds, which are committed nowhere and are rendered here
 *    through `renderMaterializedKindIndex`, the same production function the CLI
 *    materializes `.defold-types/<id>/kinds/` with;
 * 4. ref-doc targets, excluded by `refDocSkippedTargets`.
 */
export async function exampleSurfaces(
  targets: readonly ApiTarget[] = loadApiTargets(),
): Promise<ExampleSurface[]> {
  const surfaces: ExampleSurface[] = [];
  for (const target of committedTargets(targets)) {
    const runtime = loadTargetModules(target);
    const editor = loadTargetEditorModules(target);
    const generatedDir = resolve(PACKAGE_ROOT, target.generatedDir);
    const isDefault = target.default === true;
    const manifest = targetKindManifest(target);
    // The aggregate entrypoint is the runtime surface: importing the editor VM
    // there would drag it into every program that pins the version.
    const rootModules = new Set(runtime.map((module) => moduleKey(module.namespace, "runtime")));

    surfaces.push({
      id: target.id,
      targetId: target.id,
      kind: null,
      origin: "committed",
      // The default target's aggregate entrypoint is the package root itself;
      // a versioned target commits its own index beside its modules.
      entry: isDefault ? resolve(PACKAGE_ROOT, "index.d.ts") : resolve(generatedDir, "index.d.ts"),
      virtualFiles: [],
      modules: rootModules,
      exports: isDefault ? defaultRootExports(manifest) : NO_EXPORTS,
    });

    const materialized = isDefault
      ? null
      : await materializedRuntimeKindFiles(target, resolve(VIRTUAL_ROOT, target.id));

    for (const entry of manifest) {
      const modules = kindModules(entry, runtime, editor);
      const committedPath = resolve(generatedDir, "kinds", `${entry.kind}.d.ts`);
      const rendered = materialized?.kinds.find((kind) => kind.entry.kind === entry.kind);
      surfaces.push({
        id: `${target.id}/kinds/${entry.kind}`,
        targetId: target.id,
        kind: entry.kind,
        origin: rendered ? "materialized" : "committed",
        entry: rendered ? rendered.path : committedPath,
        virtualFiles: rendered ? (materialized?.files ?? []) : [],
        modules,
        exports: kindExports(entry),
      });
    }
  }
  return surfaces;
}

/**
 * `<fqn>:<sourceHash>` -> the ids of every surface shipping that body. Built by
 * hashing each target's own manifest documents with the same normalization
 * `example-store.ts` pins with, so a translation is judged against the
 * declarations that actually carry it.
 *
 * Keyed on the *document*, never on which generated file physically holds the
 * body: `api-targets.json` skips `go.get`/`set`/`property`, `msg.post`/`url`,
 * `render.render_target` and six `vmath` functions in favour of the
 * hand-authored `src/*-overloads.d.ts`, and a file-keyed resolver strands every
 * one of them as unowned.
 */
export function translationOwnership(
  store: TranslationStore,
  surfaces: readonly ExampleSurface[],
  targets: readonly ApiTarget[] = loadApiTargets(),
): Map<string, string[]> {
  const stored = new Set(
    Object.entries(store).flatMap(([fqn, entries]) =>
      entries.map((entry) => exampleIdentity(fqn, entry.sourceHash)),
    ),
  );
  const owners = new Map<string, string[]>();
  for (const target of committedTargets(targets)) {
    const modules = [
      ...loadTargetModules(target).map((module) => ({ module, lane: "runtime" as const })),
      ...loadTargetEditorModules(target).map((module) => ({ module, lane: "editor" as const })),
    ];
    const targetSurfaces = surfaces.filter((surface) => surface.targetId === target.id);
    for (const { module, lane } of modules) {
      const key = moduleKey(module.namespace, lane);
      const carriers = targetSurfaces.filter((surface) => surface.modules.has(key));
      if (carriers.length === 0) continue;
      for (const fn of parseDefoldApiDoc(module.doc).functions) {
        const lua = htmlToCodeText(fn.examples ?? "");
        if (lua === "") continue;
        const identity = exampleIdentity(fn.name, hashExampleSource(lua));
        if (!stored.has(identity)) continue;
        const existing = owners.get(identity) ?? [];
        for (const surface of carriers) {
          if (!existing.includes(surface.id)) existing.push(surface.id);
        }
        owners.set(identity, existing);
      }
    }
  }
  return owners;
}

/** Stored translations no shipping surface carries — an authored body nothing emits. */
export function unownedTranslations(
  store: TranslationStore,
  surfaces: readonly ExampleSurface[],
  targets: readonly ApiTarget[] = loadApiTargets(),
): string[] {
  const owners = translationOwnership(store, surfaces, targets);
  const out: string[] = [];
  for (const [fqn, entries] of Object.entries(store)) {
    for (const entry of entries) {
      const identity = exampleIdentity(fqn, entry.sourceHash);
      if ((owners.get(identity) ?? []).length === 0) out.push(identity);
    }
  }
  return out.sort();
}
