/**
 * Which shipping declaration surface carries which hand-authored `@example`
 * translation.
 *
 * The store is not single-surface: an FQN maps to one translation per distinct
 * example body (`example-store.ts`), and sibling entries serve *different*
 * targets, because an older target keeps shipping the body a re-pin replaced.
 * Judging every translation against the default entrypoint is therefore the
 * wrong comparison — it reports the editor examples as unresolved names and
 * measures bodies against signatures from a target that never shipped them.
 *
 * Membership is read from each target's own manifest documents and never
 * inferred from hash recency, because the same body legitimately ships in a
 * current target and a versioned one at the same time.
 */
import { basename, dirname, resolve } from "node:path";
import ts from "typescript";
import { parseDefoldApiDoc } from "../src/api-doc";
import { htmlToCodeText, splitExampleSources } from "../src/doc-comment";
import { hashExampleSource, type TranslationStore } from "../src/example-store";
import { buildVersionedSurfaceFiles, renderMaterializedKindIndex } from "./materialize-version";
import {
  type ApiTarget,
  KIND_MODULE_MANIFEST,
  type KindManifestEntry,
  loadApiTargets,
  loadTargetEditorModules,
  loadTargetModules,
  type ModuleManifestEntry,
  RESTRICTED_NAMESPACES,
  RESTRICTED_SRC_AUGMENTATIONS,
  targetKindManifest,
} from "./regen";

const PACKAGE_ROOT = resolve(import.meta.dir, "..");

// A materialized surface exists only as bytes, but its module specifiers still
// resolve like a real one: its relative `../<module>` imports reach the sibling
// virtual files, and `@defold-typescript/types/lifecycle` reaches the package's
// own `src/` through the gate's `paths` mapping (`example-typecheck.ts`), which
// stands in for the install the CLI's on-disk `.defold-types/<id>/` sits inside.
const VIRTUAL_ROOT = resolve(PACKAGE_ROOT, ".example-gate");

export interface SurfaceFile {
  /** Absolute path. Real for a committed surface, virtual for a materialized one. */
  readonly path: string;
  readonly contents: string;
}

export interface ExampleSurface {
  /** `<target>` for a root entrypoint, `<target>/kinds/<kind>` for a kind. */
  readonly id: string;
  readonly targetId: string;
  /** `null` for the aggregate root entrypoint. */
  readonly kind: string | null;
  readonly origin: "committed" | "materialized";
  readonly entry: string;
  /** Empty for a committed surface; the whole in-memory tree for a materialized one. */
  readonly virtualFiles: readonly SurfaceFile[];
  /** The manifest modules this entrypoint reaches, as `moduleKey` values. */
  readonly modules: ReadonlySet<string>;
  /**
   * The names this entrypoint *exports*, as opposed to the ambient declarations
   * it pulls in. A kind subpath re-exports its factory (`defineScript` and
   * friends); a user writing a script imports them, so an example fragment
   * compiled without them is judged against a surface nobody consumes.
   */
  readonly exports: SurfaceExports;
}

export interface SurfaceExports {
  readonly values: readonly string[];
  readonly types: readonly string[];
}

const NO_EXPORTS: SurfaceExports = { values: [], types: [] };

/**
 * The package root's export set. `index.d.ts` ends in `export * from
 * "./src/index"`, which re-exports every kind factory and the script-property
 * types — but not a kind's `extraExports`, which stay on the editor subpath. A
 * versioned root is generated by `generateVersionIndex` and ends in a bare
 * `export {}`, so it exports nothing and takes `NO_EXPORTS` instead.
 *
 * Nothing here is taken on trust: the gate imports these names, so a root that
 * stopped exporting one fails every unit on that surface with TS2305 rather than
 * quietly widening what counts as fragment context.
 */
function defaultRootExports(manifest: readonly KindManifestEntry[]): SurfaceExports {
  return {
    values: manifest.map((entry) => entry.factory),
    types: ["ScriptProperties", "ScriptProperty"],
  };
}

/**
 * The kind subpath's export set, read from the same manifest entry
 * `generateKindIndex` and `renderMaterializedKindIndex` render their export
 * clause from, so a kind that gains an export reaches the gate with no second
 * edit.
 */
function kindExports(entry: KindManifestEntry): SurfaceExports {
  return {
    values: [entry.factory, ...(entry.extraExports ?? [])],
    types: [
      ...(entry.extraTypeExports ?? []),
      ...(entry.propertyTypes === false ? [] : ["ScriptProperties", "ScriptProperty"]),
    ],
  };
}

/**
 * A manifest module's identity within a target. The lane has to be part of it:
 * `http`, `image`, `json` and `zlib` name *both* a runtime namespace and an
 * editor-VM one, so a bare namespace would put the runtime `zlib.inflate` on the
 * editor kind (which does not carry it) and vice versa.
 */
export function moduleKey(namespace: string, lane: "runtime" | "editor"): string {
  return `${lane}:${namespace}`;
}

export interface SkippedTarget {
  readonly id: string;
  readonly reason: string;
}

/** `<fqn>:<sourceHash>` — one authored translation, independent of surface. */
export function exampleIdentity(fqn: string, sourceHash: string): string {
  return `${fqn}:${sourceHash}`;
}

/**
 * Targets an offline gate cannot honestly cover. A `ref-doc` target resolves its
 * documents from a zip downloaded on demand, so nothing is vendored to compile
 * against. The exclusion is returned rather than left to a missing directory, so
 * vendoring such a target later is a visible change instead of a silent one.
 */
export function refDocSkippedTargets(
  targets: readonly ApiTarget[] = loadApiTargets(),
): SkippedTarget[] {
  return targets
    .filter((target) => (target.source ?? null) !== null)
    .map((target) => ({
      id: target.id,
      reason: `documents are not vendored (source kind "${target.source?.kind}")`,
    }));
}

function committedTargets(targets: readonly ApiTarget[] = loadApiTargets()): ApiTarget[] {
  return targets.filter((target) => (target.source ?? null) === null);
}

/**
 * The namespaces one kind entrypoint reaches, derived from the same manifests
 * `generateKindIndex` renders from. An `only` kind is built from its target's
 * editor documents and is disjoint from the runtime surface; every other kind
 * takes the universal set plus, for a restricted kind, its own namespace.
 */
function kindModules(
  entry: KindManifestEntry,
  runtime: readonly ModuleManifestEntry[],
  editor: readonly ModuleManifestEntry[],
): Set<string> {
  if (entry.only !== undefined) {
    return new Set(editor.map((module) => moduleKey(module.namespace, "editor")));
  }
  return new Set(
    runtime
      .map((module) => module.namespace)
      .filter(
        (namespace) =>
          !Object.hasOwn(RESTRICTED_NAMESPACES, namespace) || entry.restricted === namespace,
      )
      .map((namespace) => moduleKey(namespace, "runtime")),
  );
}

/**
 * Reproduce the CLI's materialized surface as an in-memory file map. Mirrors
 * `materializeRefDocSurface`: the generator builds the self-contained surface,
 * and this adds the per-kind subpaths through the production renderer. Only the
 * runtime kinds are rendered here — a target's editor kind is committed under
 * `generated/versions/<id>/kinds/`, so it is read from disk instead.
 */
async function materializedRuntimeKindFiles(
  target: ApiTarget,
  virtualRoot: string,
): Promise<{ files: SurfaceFile[]; kinds: { entry: KindManifestEntry; path: string }[] }> {
  const built = await buildVersionedSurfaceFiles(target);
  const files: SurfaceFile[] = built.map((file) => ({
    path: resolve(virtualRoot, file.path),
    contents: file.contents,
  }));

  const editorOwned = new Set(
    (target.editorModules ?? []).map((module) => module.outFile.replace(/\.d\.ts$/, "")),
  );
  const surfaceModules = files
    .filter((file) => dirname(file.path) === virtualRoot && file.path.endsWith(".d.ts"))
    .map((file) => basename(file.path).replace(/\.d\.ts$/, ""))
    .filter(
      (base) =>
        base !== "index" &&
        base !== "core-types" &&
        base !== "engine-globals" &&
        !editorOwned.has(base),
    )
    .sort();
  const universalModules = surfaceModules.filter(
    (base) =>
      !Object.hasOwn(RESTRICTED_NAMESPACES, base) &&
      !Object.hasOwn(RESTRICTED_SRC_AUGMENTATIONS, base),
  );

  const kinds: { entry: KindManifestEntry; path: string }[] = [];
  for (const entry of targetKindManifest(target)) {
    if (entry.only !== undefined) continue;
    const path = resolve(virtualRoot, "kinds", `${entry.kind}.d.ts`);
    files.push({
      path,
      contents: renderMaterializedKindIndex({
        kind: entry.kind,
        universalModules,
        restrictedModule:
          entry.restricted && surfaceModules.includes(entry.restricted) ? entry.restricted : null,
        restrictedAugmentations: surfaceModules.filter(
          (base) =>
            Object.hasOwn(RESTRICTED_SRC_AUGMENTATIONS, base) &&
            entry.restricted !== undefined &&
            RESTRICTED_SRC_AUGMENTATIONS[base] === entry.restricted,
        ),
      }),
    });
    kinds.push({ entry, path });
  }
  return { files, kinds };
}

/**
 * Every surface this gate can reach offline. Not the same as every surface a
 * user can install: the four families differ in how they exist, and conflating
 * them produces path claims that are simply false.
 *
 * 1. the default target's root and all four committed kind entrypoints;
 * 2. each versioned target's committed root, and its committed editor kinds —
 *    `regen.ts` filters the kind manifest to `entry.only !== undefined` before
 *    writing `versions/<id>/kinds/`, so that directory is never the runtime trio;
 * 3. versioned runtime kinds, which are committed nowhere and are rendered here
 *    through `renderMaterializedKindIndex`, the same production function the CLI
 *    materializes `.defold-types/<id>/kinds/` with;
 * 4. ref-doc targets, excluded by `refDocSkippedTargets`.
 */
export async function exampleSurfaces(
  targets: readonly ApiTarget[] = loadApiTargets(),
): Promise<ExampleSurface[]> {
  const surfaces: ExampleSurface[] = [];
  for (const target of committedTargets(targets)) {
    const runtime = loadTargetModules(target);
    const editor = loadTargetEditorModules(target);
    const generatedDir = resolve(PACKAGE_ROOT, target.generatedDir);
    const isDefault = target.default === true;
    const manifest = targetKindManifest(target);
    // The aggregate entrypoint is the runtime surface: importing the editor VM
    // there would drag it into every program that pins the version.
    const rootModules = new Set(runtime.map((module) => moduleKey(module.namespace, "runtime")));

    surfaces.push({
      id: target.id,
      targetId: target.id,
      kind: null,
      origin: "committed",
      // The default target's aggregate entrypoint is the package root itself;
      // a versioned target commits its own index beside its modules.
      entry: isDefault ? resolve(PACKAGE_ROOT, "index.d.ts") : resolve(generatedDir, "index.d.ts"),
      virtualFiles: [],
      modules: rootModules,
      exports: isDefault ? defaultRootExports(manifest) : NO_EXPORTS,
    });

    const materialized = isDefault
      ? null
      : await materializedRuntimeKindFiles(target, resolve(VIRTUAL_ROOT, target.id));

    for (const entry of manifest) {
      const modules = kindModules(entry, runtime, editor);
      const committedPath = resolve(generatedDir, "kinds", `${entry.kind}.d.ts`);
      const rendered = materialized?.kinds.find((kind) => kind.entry.kind === entry.kind);
      surfaces.push({
        id: `${target.id}/kinds/${entry.kind}`,
        targetId: target.id,
        kind: entry.kind,
        origin: rendered ? "materialized" : "committed",
        entry: rendered ? rendered.path : committedPath,
        virtualFiles: rendered ? (materialized?.files ?? []) : [],
        modules,
        exports: kindExports(entry),
      });
    }
  }
  return surfaces;
}

/**
 * `<fqn>:<sourceHash>` -> the ids of every surface shipping that body. Built by
 * hashing each target's own manifest documents with the same normalization
 * `example-store.ts` pins with, so a translation is judged against the
 * declarations that actually carry it.
 *
 * Keyed on the *document*, never on which generated file physically holds the
 * body: `api-targets.json` skips `go.get`/`set`/`property`, `msg.post`/`url`,
 * `render.render_target` and six `vmath` functions in favour of the
 * hand-authored `src/*-overloads.d.ts`, and a file-keyed resolver strands every
 * one of them as unowned.
 */
export function translationOwnership(
  store: TranslationStore,
  surfaces: readonly ExampleSurface[],
  targets: readonly ApiTarget[] = loadApiTargets(),
): Map<string, string[]> {
  const stored = new Set(
    Object.entries(store).flatMap(([fqn, entries]) =>
      entries.map((entry) => exampleIdentity(fqn, entry.sourceHash)),
    ),
  );
  const owners = new Map<string, string[]>();
  for (const target of committedTargets(targets)) {
    const modules = [
      ...loadTargetModules(target).map((module) => ({ module, lane: "runtime" as const })),
      ...loadTargetEditorModules(target).map((module) => ({ module, lane: "editor" as const })),
    ];
    const targetSurfaces = surfaces.filter((surface) => surface.targetId === target.id);
    for (const { module, lane } of modules) {
      const key = moduleKey(module.namespace, lane);
      const carriers = targetSurfaces.filter((surface) => surface.modules.has(key));
      if (carriers.length === 0) continue;
      for (const fn of parseDefoldApiDoc(module.doc).functions) {
        const lua = htmlToCodeText(fn.examples ?? "");
        if (lua === "") continue;
        // Both keyings, because both are live: an element documented as several
        // examples is stored one entry per segment, one documented as a single
        // blob under the whole-blob hash. Registering only the blob would strand
        // every split body with no owning surface.
        const segments = splitExampleSources(fn.examples ?? "");
        const hashes = [
          hashExampleSource(lua),
          ...(segments.length > 1
            ? segments.map((segment) => hashExampleSource(segment.code))
            : []),
        ];
        for (const hash of hashes) {
          const identity = exampleIdentity(fn.name, hash);
          if (!stored.has(identity)) continue;
          const existing = owners.get(identity) ?? [];
          for (const surface of carriers) {
            if (!existing.includes(surface.id)) existing.push(surface.id);
          }
          owners.set(identity, existing);
        }
      }
    }
  }
  return owners;
}

/**
 * The kind factory names a translation can call, read from the manifest that
 * renders every kind subpath's export clause — so a kind added there, or a
 * factory renamed there, reaches the binding below with no second edit.
 */
export function kindFactoryNames(): readonly string[] {
  return KIND_MODULE_MANIFEST.map((entry) => entry.factory);
}

/**
 * `translationOwnership`'s result narrowed to the surfaces that can actually
 * satisfy the body. Ownership answers *which surfaces ship this documentation*;
 * this answers *which of them export the names the body imports*. A body
 * calling `defineScript` is script-kind code by construction, so judging it on
 * `kinds/gui-script` — which exports `defineGuiScript` instead — reports a fact
 * about the surface, not a defect in the example.
 *
 * The match is on the manifest's own factory names at a word boundary, never on
 * the shape of the resulting diagnostic: excusing `Cannot find name 'define*'`
 * would also excuse `defineScrpt`, and a misspelled API is exactly what the
 * gate exists to catch. A near-miss identifier narrows nothing and stays judged
 * on every surface its documentation reaches.
 */
export function factoryBoundOwnership(
  store: TranslationStore,
  owners: ReadonlyMap<string, readonly string[]>,
  surfaces: readonly ExampleSurface[],
): Map<string, string[]> {
  const factories = kindFactoryNames();
  const exportsById = new Map(
    surfaces.map((surface) => [surface.id, new Set(surface.exports.values)] as const),
  );
  const bound = new Map<string, string[]>();
  for (const [identity, ids] of owners) bound.set(identity, [...ids]);
  for (const [fqn, entries] of Object.entries(store)) {
    for (const entry of entries) {
      const identity = exampleIdentity(fqn, entry.sourceHash);
      const ids = bound.get(identity);
      if (ids === undefined) continue;
      const called = factories.filter((name) => new RegExp(`\\b${name}\\b`).test(entry.ts));
      if (called.length === 0) continue;
      bound.set(
        identity,
        ids.filter((id) => {
          const values = exportsById.get(id);
          return values !== undefined && called.every((name) => values.has(name));
        }),
      );
    }
  }
  return bound;
}

/**
 * Every module namespace the inventory reaches, with the lane dropped — read
 * from each surface's own `modules` set, so a target that gains or renames a
 * namespace reaches the binding below with no second edit.
 */
export function moduleNamespaces(surfaces: readonly ExampleSurface[]): ReadonlySet<string> {
  const namespaces = new Set<string>();
  for (const surface of surfaces) {
    for (const key of surface.modules) namespaces.add(key.slice(key.indexOf(":") + 1));
  }
  return namespaces;
}

/**
 * The module namespaces a body actually reads, as the identifier of each
 * property access rooted in a known namespace.
 *
 * This has to parse rather than scan. `editor.create_resources` carries the
 * string literal `"go.property('hp', 100)"`; a `\bgo\s*\.` match reads that as a
 * `go` usage, demands a surface carrying both `go` and `editor`, finds none, and
 * empties the body's owner list. A walk over property-access expressions reads
 * it as a string and narrows nothing.
 */
export function referencedNamespaces(
  source: string,
  known: ReadonlySet<string>,
): readonly string[] {
  const parsed = ts.createSourceFile("body.ts", source, ts.ScriptTarget.Latest, true);
  const found = new Set<string>();
  const visit = (node: ts.Node): void => {
    if (ts.isPropertyAccessExpression(node)) {
      const chain = dottedChain(node.expression);
      const namespace = chain === undefined ? undefined : longestKnownNamespace(chain, known);
      if (namespace !== undefined) {
        found.add(namespace);
        // The receiver of a resolved chain holds only that namespace's own
        // prefixes. Descending would resolve `tilemap.tiles` again as bare
        // `tilemap`, and demand a surface carrying both.
        return;
      }
    }
    ts.forEachChild(node, visit);
  };
  visit(parsed);
  return [...found].sort();
}

/** The receiver's dotted text when it is built only from identifiers and property accesses. */
function dottedChain(node: ts.Expression): string | undefined {
  if (ts.isIdentifier(node)) return node.text;
  if (!ts.isPropertyAccessExpression(node)) return undefined;
  const head = dottedChain(node.expression);
  return head === undefined ? undefined : `${head}.${node.name.text}`;
}

/**
 * The longest prefix of a dotted receiver that the surfaces declare as a
 * namespace. `tilemap.tiles` is a namespace of its own, carried only by the
 * editor-script kinds, and its bare head `tilemap` is a different namespace
 * neither of them carries — so matching the head would demand a surface that
 * does not exist and strand the body.
 */
export function longestKnownNamespace(
  chain: string,
  known: ReadonlySet<string>,
): string | undefined {
  const parts = chain.split(".");
  for (let end = parts.length; end > 0; end -= 1) {
    const candidate = parts.slice(0, end).join(".");
    if (known.has(candidate)) return candidate;
  }
  return undefined;
}

/**
 * `translationOwnership`'s result narrowed a second way: to the surfaces whose
 * declarations carry every module namespace the body reads. Ownership answers
 * *which surfaces ship this documentation*; this answers *which of them can
 * import the namespaces it reaches*. `camera.get_cameras` is documented by
 * `camera`, which every kind reaches, but drives `render.set_camera`, which the
 * script and gui kinds cannot import — so `Cannot find name 'render'` there is a
 * fact about the surface, and no edit to the body removes it.
 *
 * The lane is deliberately not part of the match. `http`, `image`, `json` and
 * `zlib` name both a runtime namespace and an editor-VM one (`moduleKey`), and
 * the body text cannot say which it meant, so a surface satisfies a reference
 * when it carries that namespace in either lane.
 */
export function moduleBoundOwnership(
  store: TranslationStore,
  owners: ReadonlyMap<string, readonly string[]>,
  surfaces: readonly ExampleSurface[],
): Map<string, string[]> {
  const known = moduleNamespaces(surfaces);
  const modulesById = new Map(surfaces.map((surface) => [surface.id, surface.modules] as const));
  const bound = new Map<string, string[]>();
  for (const [identity, ids] of owners) bound.set(identity, [...ids]);
  for (const [fqn, entries] of Object.entries(store)) {
    for (const entry of entries) {
      const identity = exampleIdentity(fqn, entry.sourceHash);
      const ids = bound.get(identity);
      if (ids === undefined) continue;
      const referenced = referencedNamespaces(entry.ts, known);
      if (referenced.length === 0) continue;
      bound.set(
        identity,
        ids.filter((id) => {
          const modules = modulesById.get(id);
          if (modules === undefined) return false;
          return referenced.every(
            (namespace) =>
              modules.has(moduleKey(namespace, "runtime")) ||
              modules.has(moduleKey(namespace, "editor")),
          );
        }),
      );
    }
  }
  return bound;
}

/**
 * The one ownership composition the gate runs: documentation ownership narrowed
 * by the factory a body calls, then by the namespaces it reads. Extracted so the
 * no-empty-owner invariant can be asserted against the order and membership
 * production actually uses, rather than against a re-composition in a test.
 */
export function boundOwnership(
  store: TranslationStore,
  surfaces: readonly ExampleSurface[],
  targets: readonly ApiTarget[] = loadApiTargets(),
): Map<string, string[]> {
  return moduleBoundOwnership(
    store,
    factoryBoundOwnership(store, translationOwnership(store, surfaces, targets), surfaces),
    surfaces,
  );
}

/** Stored translations no shipping surface carries — an authored body nothing emits. */
export function unownedTranslations(
  store: TranslationStore,
  surfaces: readonly ExampleSurface[],
  targets: readonly ApiTarget[] = loadApiTargets(),
): string[] {
  const owners = translationOwnership(store, surfaces, targets);
  const out: string[] = [];
  for (const [fqn, entries] of Object.entries(store)) {
    for (const entry of entries) {
      const identity = exampleIdentity(fqn, entry.sourceHash);
      if ((owners.get(identity) ?? []).length === 0) out.push(identity);
    }
  }
  return out.sort();
}
